version: '3'
services:
  app:
    image: sangtq989/blockchain-dapp:api
    ports:
      - "8080:8080"
    environment:
      SQL_URL: jdbc:postgresql://db:5432/mydb
      SQL_USER: myuser
      SQL_PASS: mypassword
      JWT_SECRET: veryserioussecuredprivatekey
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
