version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SQL_URL: jdbc:postgresql://db:5432/mydb
      SQL_USER: myuser
      SQL_PASS: mypassword
      JWT_SECRET: veryserioussecuredprivatekey
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: fb1361879d939e
      MAIL_PASS: 47983df0d82709
      APP_URL: http://localhost:8080
#      FRONT_END: http://localhost:4000
      MINIO_URL: http://minio:9000
#      MINIO_ACCESS_KEY: admin
#      MINIO_SECRET_KEY: 1e3q2wadSzxc
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
      - "9002:9002"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1e3q2wadSzxc
      MINIO_ACCESS_KEY: 1e3q2wadSzx
      MINIO_SECRET_KEY: qdeawszcX
    command: server --console-address ":9002" /data

volumes:
  pgdata:
  minio_storage:
