spring:
  datasource:
    url: ${SQL_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SQL_USER:postgres}
    password: ${SQL_PASS:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DLL_AUTO:update}

jwt:
  secret.key: ${JWT_SECRET:veryserioussecuredprivatekey}
  exp: ${JWT_EXP_TIME:6000}