spring:
  datasource:
    url: ${SQL_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SQL_USER:postgres}
    password: ${SQL_PASS:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DLL_AUTO:update}
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USER:fb1361879d939e}
    password: ${MAIL_PASS:47983df0d82709}

jwt:
  secret.key: ${JWT_SECRET:veryserioussecuredprivatekey}
  exp: ${JWT_EXP_TIME:6000}

blockchain-app:
  url: ${APP_URL:http://localhost:8080}

